source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'jekyll'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-github-metadata'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-twitter-plugin'
    gem 'jekyll-sitemap'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'webrick'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-imagemagick'
    gem 'jekyll-minifier'
    gem 'jekyll-link-attributes'
    gem 'jemoji'
    gem 'mini_racer'
end
